import { notFound } from 'next/navigation';
import { api, formatMoney, formatTime } from '@/lib/api';
import { DataTable, EvidencePane, PageHeading, Status, TraceItem, TraceRail } from '@/components/console';

interface Detail { payment: { id:string; status:string; captureMethod:string; amount:string; authorizedAmount:string; capturedAmount:string; refundedAmount:string; platformFeeAmount:string; currency:string; description?:string; createdAt:string }; attempts:Array<{id:string;kind:string;status:string;amount:string;currency:string;providerTransactionId?:string;createdAt:string}>; refunds:Array<{id:string;status:string;amount:string;currency:string;createdAt:string}>; ledger:Array<{transactionId:string;businessType:string;description:string;status:string;createdAt:string;accountCode:string;debit:string;credit:string}>; timeline:Array<{action:string;actorType:string;metadata:Record<string,unknown>;createdAt:string}> }
export const dynamic = 'force-dynamic';
export default async function PaymentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; let detail: Detail;
  try { detail = await api<Detail>(`/payments/${id}`); } catch { notFound(); }
  const { payment } = detail;
  const trace: TraceItem[] = detail.timeline.map((entry) => ({ label: entry.action.replaceAll('.', ' · '), detail: `${entry.actorType.toLowerCase()} · ${JSON.stringify(entry.metadata)}`, at: entry.createdAt, state: /failed/.test(entry.action) ? 'failed' : 'done' }));
  if (!['CAPTURED','PARTIALLY_REFUNDED','REFUNDED','DISPUTED'].includes(payment.status)) trace.push({ label:'Next boundary', detail:'Awaiting the next durable command or provider event', state:'active' });
  return <><PageHeading eyebrow={`payment / ${payment.id}`} title={payment.description || 'Payment evidence'}><Status value={payment.status}/> · {formatMoney(payment.amount,payment.currency)} · {payment.captureMethod.toLowerCase()} capture</PageHeading><div className="fact-strip"><div><span>authorized</span><strong>{formatMoney(payment.authorizedAmount,payment.currency)}</strong></div><div><span>captured</span><strong>{formatMoney(payment.capturedAmount,payment.currency)}</strong></div><div><span>refunded</span><strong>{formatMoney(payment.refundedAmount,payment.currency)}</strong></div><div><span>platform fee</span><strong>{formatMoney(payment.platformFeeAmount,payment.currency)}</strong></div></div><div className="detail-grid"><EvidencePane label="causal trace" title="Lifecycle evidence"><TraceRail items={trace}/></EvidencePane><EvidencePane label="provider operations" title="Attempts"><DataTable empty="No provider operation has been requested yet." columns={[{key:'kind',label:'operation'},{key:'status',label:'state'},{key:'amount',label:'amount',align:'right'},{key:'provider',label:'provider reference'}]} rows={detail.attempts.map((attempt)=>({id:attempt.id,kind:attempt.kind.toLowerCase(),status:<Status value={attempt.status}/>,amount:formatMoney(attempt.amount,attempt.currency),provider:attempt.providerTransactionId??'—'}))}/></EvidencePane></div><EvidencePane label="immutable evidence" title="Journal entries"><DataTable empty="No journal exists yet. Authorization alone does not move ledger money." columns={[{key:'business',label:'business event'},{key:'account',label:'account'},{key:'debit',label:'debit',align:'right'},{key:'credit',label:'credit',align:'right'},{key:'posted',label:'posted'}]} rows={detail.ledger.map((entry,index)=>({id:`${entry.transactionId}-${index}`,business:entry.businessType.toLowerCase(),account:entry.accountCode.replaceAll('_',' ').toLowerCase(),debit:Number(entry.debit)?formatMoney(entry.debit,payment.currency):'—',credit:Number(entry.credit)?formatMoney(entry.credit,payment.currency):'—',posted:formatTime(entry.createdAt)}))}/></EvidencePane></>;
}
